"""add a table called favourites

Revision ID: 7ce3d36ef3d9
Revises: 7739389796ab
Create Date: 2025-06-17 16:34:28.841086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce3d36ef3d9'
down_revision: Union[str, None] = '7739389796ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("favourites",
                    sa.Column('post_id', sa.Integer(), ),
                    sa.Column('user_id', sa.Integer(), ),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('post_id', 'user_id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("favourites")
    # ### end Alembic commands ###
