"""add phone number

Revision ID: d7d17b9462ab
Revises: d2ced0ee96f3
Create Date: 2025-06-13 17:30:05.299694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7d17b9462ab'
down_revision: Union[str, None] = 'd2ced0ee96f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users",sa.Column("phone_number",sa.String(),nullable=False))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("users","phone_number")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
